import { Category, Subcategory, Product } from '../types';

export const CATEGORIES: Category[] = [
  { "id": "general-lab", "name": "Общелабораторное оборудование", "span": "1x1" },
  { "id": "consumables", "name": "Расходные материалы", "span": "1x1" },
  { "id": "analytical", "name": "Аналитическое оборудование", "span": "1x1" },
  { "id": "thermo", "name": "Термостатирующее оборудование", "span": "1x1" },
  { "id": "measuring", "name": "Измерительные приборы", "span": "1x1" },
  { "id": "centrifuge", "name": "Центрифугирование", "span": "1x1" },
  { "id": "distillation", "name": "Дистилляция и фильтрация", "span": "1x1" },
  { "id": "pharmaceutical", "name": "Фармацевтическое оборудование", "span": "2x1" },
  { "id": "microscopes", "name": "Микроскопы и оптика", "span": "1x1" },
  { "id": "laminar", "name": "Ламинарные шкафы и вытяжки", "span": "1x1" },
  { "id": "cleaning", "name": "Очистка и стерилизация", "span": "1x1" },
  { "id": "furniture", "name": "Лабораторная мебель", "span": "1x1" }
];

export const SUBCATEGORIES: Subcategory[] = [
  // ВСЕ подкатегории из products.json привязываем к Центрифугированию
  { "id": "centrifuge-rotor", "categoryId": "centrifuge", "name": "Centrifuge Rotor" },
  { "id": "low-speed-centrifuge-rotor", "categoryId": "centrifuge", "name": "Low Speed Centrifuge Rotor" },
  { "id": "swing-buckets-rotor", "categoryId": "centrifuge", "name": "Swing Buckets Rotor" },
  { "id": "table-top-centrifuge-rotor", "categoryId": "centrifuge", "name": "Table Top Centrifuge Rotor" },
  { "id": "low-speed-centrifuge", "categoryId": "centrifuge", "name": "Low-Speed Centrifuge" },
  { "id": "table-top-centrifuge", "categoryId": "centrifuge", "name": "Table Top Centrifuge" },
  { "id": "blood-bank-centrifuge", "categoryId": "centrifuge", "name": "Blood Bank Centrifuge" },
  { "id": "micro-centrifuge-rotor", "categoryId": "centrifuge", "name": "Micro Centrifuge Rotor" },
  { "id": "swing-rotor", "categoryId": "centrifuge", "name": "Swing Rotor" },
  { "id": "high-speed-refrigerated-centrifuge", "categoryId": "centrifuge", "name": "High-Speed Refrigerated Centrifuge" },
  { "id": "high-speed-centrifuge", "categoryId": "centrifuge", "name": "High-Speed Centrifuge" },
  { "id": "large-capacity-refrigerated-centrifuge", "categoryId": "centrifuge", "name": "Large Capacity Refrigerated Centrifuge" },
  { "id": "centrifugal-tubes-bottles", "categoryId": "centrifuge", "name": "Centrifugal Tubes & Bottles" },
  { "id": "microplate-rotor", "categoryId": "centrifuge", "name": "Microplate Rotor" },
  { "id": "prp-centrifuge-rotor", "categoryId": "centrifuge", "name": "PRP Centrifuge Rotor" },
  { "id": "microscope", "categoryId": "centrifuge", "name": "Microscope" },
  { "id": "floor-standing-centrifuge", "categoryId": "centrifuge", "name": "Floor-standing Centrifuge" },
  { "id": "special-rotor", "categoryId": "centrifuge", "name": "Special Rotor" },
  { "id": "floor-standing-centrifuge-rotor", "categoryId": "centrifuge", "name": "Floor-Standing Centrifuge Rotor" },
  { "id": "low-speed-refrigerated-centrifuge", "categoryId": "centrifuge", "name": "Low Speed Refrigerated Centrifuge" },
  { "id": "vacuum-centrifugal-concentrator", "categoryId": "centrifuge", "name": "Vacuum Centrifugal Concentrator" },
  { "id": "mini-centrifuge", "categoryId": "centrifuge", "name": "MINI Centrifuge" },
  { "id": "tube-sealer", "categoryId": "centrifuge", "name": "Tube Sealer" },
  { "id": "prp-cgfstem-cell-centrifuge", "categoryId": "centrifuge", "name": "PRP /CGF/Stem Cell Centrifuge" },
  { "id": "vacuum-freezer-dryer-lyophilizer", "categoryId": "centrifuge", "name": "Vacuum Freezer Dryer/ Lyophilizer" },
  { "id": "gel-card-centrifuge-rotor", "categoryId": "centrifuge", "name": "Gel card centrifuge rotor" },
  { "id": "7000rpm", "categoryId": "centrifuge", "name": "7000RPM" },
  { "id": "incubator", "categoryId": "centrifuge", "name": "Incubator" },
  { "id": "lab-vacuum-freezer-dryer-lyophilizer", "categoryId": "centrifuge", "name": "Lab Vacuum Freezer Dryer/ Lyophilizer" },
  { "id": "gel-card-centrifugeincubator", "categoryId": "centrifuge", "name": "Gel Card Centrifuge/Incubator" },
  { "id": "gel-card-incubator", "categoryId": "centrifuge", "name": "Gel Card Incubator" },
  { "id": "12000rpm", "categoryId": "centrifuge", "name": "12000RPM" },
  { "id": "3000rpm", "categoryId": "centrifuge", "name": "3000RPM" },
  { "id": "autoclave", "categoryId": "centrifuge", "name": "Autoclave" },
  { "id": "pilot-scale-lyophilizer", "categoryId": "centrifuge", "name": "Pilot Scale Lyophilizer" },
  { "id": "plasma-filler-maker", "categoryId": "centrifuge", "name": "Plasma Filler Maker" },
  { "id": "oil-test-centrifuge", "categoryId": "centrifuge", "name": "Oil Test Centrifuge" },
  { "id": "cell-washer-centrifuge", "categoryId": "centrifuge", "name": "Cell Washer Centrifuge" },
  { "id": "cyto-smear-liquid-centrifuge", "categoryId": "centrifuge", "name": "Cyto Smear Liquid Centrifuge" },
  { "id": "hematocrit-centrifuge", "categoryId": "centrifuge", "name": "Hematocrit Centrifuge" }
];
